### ISSUE TITLE
C2 fails to compile on FastLED with this repo

### ISSUE THREAD

**Issue by zackees** [Jason2866/platform-espressif32#81] opened 2024-09-19 17:23 UTC
[![esp32c2](https://github.com/FastLED/FastLED/actions/workflows/build_esp32c2.yml/badge.svg)](https://github.com/FastLED/FastLED/actions/workflows/build_esp32c2.yml)

Let me know if I'm doing anything wrong. Here is my board defs for this product:

```python
ESP32_C2_DEVKITM_1 = Board(
    board_name="esp32-c2-devkitm-1",
    platform_needs_install=True,  # Install platform package to get the boards
    platform="https://github.com/Jason2866/platform-espressif32",  # No support from PIO, have forked repo
)
```

**Comment by Jason2866** [comment] 2024-09-19 18:41
CI example compiles fine with the C2
https://github.com/Jason2866/platform-espressif32/blob/fc0da1b9edc2548cbe882b65e6e3df794d1c51d2/examples/arduino-blink/platformio.ini#L23
https://github.com/Jason2866/platform-espressif32/actions/runs/10937501644/job/30363510554

Don't know what you show. Not a usual Platformio setup.

**Comment by Jason2866** [comment] 2024-09-19 18:50
Don't know the context but this is not a valid platform entry
```
platform = https://github.com/Jason2866/platform-espressif32
```
use
```
platform = https://github.com/Jason2866/platform-espressif32.git
```

**Comment by Jason2866** [comment] 2024-09-19 19:58
Closing since not reproducable. C2 compiles successfully and flashing does work as expected

**Closed as completed by Jason2866** 2024-09-19 19:58 UTC

**Comment by zackees** [comment] 2024-09-19 23:43
So the issue here is that `pio ci` didn't work, but `pio run` will.

I was able to create a hack that made it work for this board but holy crap.

The good news is that now we have a new way to compile stubborn boards not officially supported so overall a huge win.
