### ISSUE TITLE
The command line is too long. (windows) vs linux  in  examples/espidf-ulp-riscv  

### ISSUE THREAD

**Issue by newmansnj** [Jason2866/platform-espressif32#60] opened 2024-02-09 05:45 UTC
examples/espidf-ulp-riscv
When I try to run your example on Windwos with framework = arduino, espidf I get the error message "The command line is too long" on linux the error message does not appear with the exact same project. The same error message appears when I run framework espidf (without arduino ) but with platform = https://github.com/tasmota/platform-espressif32/releases/download/2024.01.12/platform-espressif32.zip or platform = espressif32 only with an exact version number @ ^ it does not appear because then the name for the version is smaller, no long strings follow for the exact espressif32 version.  

The reason is the cmd which is executed in windows and has a character limit of 8191. 

Linux
![Bildschirmfoto vom 2024-02-09 05-45-58](https://github.com/Jason2866/platform-espressif32/assets/110606942/c33b8420-c4c5-4512-832e-9b2aab8b0ff1)

WIndows : 
![image](https://github.com/Jason2866/platform-espressif32/assets/110606942/8f5ad8d1-a966-46a2-a050-295dde926013)
(Die Befehlszeile ist zu lang. == The command line is too long.)

**Comment by Jason2866** [comment] 2024-02-09 10:58
Don't know how i should fix a Windows issue. Not using Windows.
The platform string length seems not relevant. This path is nowhere in the called command line.

**Comment by Jason2866** [comment] 2024-02-09 13:15
Maybe this? https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/The-Windows-10-default-path-length-limitation-MAX-PATH-is-256-characters.html

**Comment by newmansnj** [comment] 2024-02-09 16:47
No, the problem is the platform an outdated API uses what is still from DO's times, which limits the characters length to 8191.

https://github.com/platformio/platformio-core/blob/f519a9d5248df3c50b0351b314cf5b090f0893b4/platformio/debug/process/gdb.py#L172

https://github.com/platformio/platformio-core/pull/4856

**Comment by Jason2866** [comment] 2024-02-09 18:36
Closing since the issue is not in the fork of platform espressif32

**Closed as completed by Jason2866** 2024-02-09 18:36 UTC
Labels: help wanted, invalid, wontfix
